Revert "update syntax"
This reverts commit 9ccc8a5e2ed0f224d72f3df3d97eceab9fd82555.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,104 +7,103 @@ addons:
   apt:
     packages:
       - xvfb
-after_success:
-  - "echo 'travis_fold:start:codecov'"
-  - codecov
-  - "npm run codecov"
-  - "echo 'travis_fold:end:codecov'"
-before_script:
-  - |
-      if [! -n "$GRUNT_TESTS"]; then
-        # Vagrant is not used on travis: This user is just for the database.
-        createuser --createdb --no-superuser --no-createrole vagrant;
-        createdb -O vagrant refinery;
-        sudo mkdir /data; # In vagrant, this is created by puppet; In production, this is an EBS mount.
-        sudo chown $USER /data;
-        cd refinery;
-        # See http://www.stuartellis.eu/articles/erb/#running-erb-from-the-command-line
-        erb config/config.json.erb > config/config.json;
-        python manage.py migrate --noinput;
-        cd ../;
-      fi
-      - if [! -n "$DJANGO_UNIT_TESTS"]; then
-          cd refinery;
-          npm install -g grunt-cli@0.1.13 bower@1.7.7 --progress false --quiet || ( cat npm-debug.log && false );
-          cd ui;
-          npm install --progress false --quiet || ( cat npm-debug.log && false );
-          bower install --config.interactive=false --quiet;
-          cd ../;
-        fi
-cache: pip
-env:
-  global:
-    - "PYTHONPATH=$PYTHONPATH:../refinery:../refinery/config"
-    - DJANGO_SETTINGS_MODULE=config.settings.prod
-install:
-  - |
-      if [! -n "$DJANGO_UNIT_TESTS"]; then
-        node --version;
-        NODE_VERSION=6.11.0;
-        nvm install $NODE_VERSION;
-        nvm use $NODE_VERSION;
-        node --version;
-        npm --version;
-        npm install -g npm@3.10.10;
-        npm --version;
-      fi
-  - |
-      if [! -n "$GRUNT_TESTS"]; then
-        pip install -r requirements.txt --quiet;
-      fi
-  - |
-      if [-n "$DJANGO_SELENIUM_TESTS"]; then
-        # Install geckodriver required for selenium testing
-        GECKODRIVER_VERSION=v0.17.0;
-        TAR=geckodriver-$GECKODRIVER_VERSION-linux64.tar;
-        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/$TAR.gz;
-        gunzip $TAR.gz;
-        tar -xvf $TAR;
-        chmod a+x geckodriver;
-        export PATH=$PATH:`pwd`;
-      fi
-language: python
+
+python:
+  - 2.7
+
+services:
+  - postgresql
+
 matrix:
   include:
-    -
-      env: GRUNT_TESTS=True
-    -
-      env: DJANGO_SELENIUM_TESTS=True
-    -
-      env: DJANGO_UNIT_TESTS=True
+    - env: GRUNT_TESTS=True
+    - env: DJANGO_SELENIUM_TESTS=True
+    - env: DJANGO_UNIT_TESTS=True
+
+install:
+  - if [! -n "$DJANGO_UNIT_TESTS"]; then
+      node --version;
+      NODE_VERSION=6.11.0;
+      nvm install $NODE_VERSION;
+      nvm use $NODE_VERSION;
+      node --version;
+      npm --version;
+      npm install -g npm@3.10.10;
+      npm --version;
+    fi
+
+  - if [! -n "$GRUNT_TESTS"]; then
+      pip install -r requirements.txt --quiet;
+    fi
+
+  - if [-n "$DJANGO_SELENIUM_TESTS"]; then
+      # Install geckodriver required for selenium testing
+      GECKODRIVER_VERSION=v0.17.0;
+      TAR=geckodriver-$GECKODRIVER_VERSION-linux64.tar;
+      wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/$TAR.gz;
+      gunzip $TAR.gz;
+      tar -xvf $TAR;
+      chmod a+x geckodriver;
+      export PATH=$PATH:`pwd`;
+    fi
+env:
+  global:
+    # These env vars are available to every build
+    - PYTHONPATH=$PYTHONPATH:../refinery:../refinery/config
+    - DJANGO_SETTINGS_MODULE=config.settings.prod
+
+before_script:
+  - if [! -n "$GRUNT_TESTS"]; then
+      # Vagrant is not used on travis: This user is just for the database.
+      createuser --createdb --no-superuser --no-createrole vagrant;
+      createdb -O vagrant refinery;
+      sudo mkdir /data; # In vagrant, this is created by puppet; In production, this is an EBS mount.
+      sudo chown $USER /data;
+      cd refinery;
+      # See http://www.stuartellis.eu/articles/erb/#running-erb-from-the-command-line
+      erb config/config.json.erb > config/config.json;
+      python manage.py migrate --noinput;
+      cd ../;
+    fi
+  - if [! -n "$DJANGO_UNIT_TESTS"]; then
+      cd refinery;
+      npm install -g grunt-cli@0.1.13 bower@1.7.7 --progress false --quiet || ( cat npm-debug.log && false );
+      cd ui;
+      npm install --progress false --quiet || ( cat npm-debug.log && false );
+      bower install --config.interactive=false --quiet;
+      cd ../;
+    fi
+script:
+  - set -e # Any error will cause travis to exit early and report a failure.
+
+  - if [! -n "$GRUNT_TESTS"]; then
+    # TODO: Not the same behavior as pre-commit hook.
+    # https://github.com/refinery-platform/refinery-platform/issues/1851
+    flake8 --exclude=migrations,ui ..;
+  fi
+
+  - echo 'travis_fold:start:grunt'
+  - pushd ui
+  - if ! -n "$DJANGO_UNIT_TESTS"; then grunt make; fi
+  - if -n "$GRUNT_TESTS"; then grunt test; fi
+  - popd
+  - echo 'travis_fold:end:grunt'
+
+  - echo 'travis_fold:start:django-unit-tests'
+  - if -n "$DJANGO_UNIT_TESTS"; then coverage run manage.py test; fi
+  - echo 'travis_fold:end:django-unit-tests'
+
+  - echo 'travis_fold:start:django-selenium-tests'
+  - if -n "$DJANGO_SELENIUM_TESTS"; then coverage run manage.py test --pattern="selenium_tests.py"; fi
+  - echo 'travis_fold:end:django-selenium-tests'
+
+  - set +e # Currently, codecov does not always exit with 0, but that should not cause travis to fail.
+
+after_success:
+  - echo 'travis_fold:start:codecov'
+  - codecov
+  - npm run codecov
+  - echo 'travis_fold:end:codecov'
 notifications:
   slack:
     secure: nDs9Oj08nRizuD0edl6WcrSgaTPMyITQjZc4qPZpt+yOxUehWbrAmVhqYypfyvdj4qSi1E72rPTXftuBB1E1IZBgX4CCkrCkWGLgIxHaaValTd64oOX66eC3BbSehQxuJB7w1DWw54xBUkTy6+ufjAqiwhLpoEUeE296urAWYHU=
-python:
-  - 2.7
-script:
-  - "set -e"
-  - |
-      if [! -n "$GRUNT_TESTS"]; then
-        # TODO: Not the same behavior as pre-commit hook.
-        # https://github.com/refinery-platform/refinery-platform/issues/1851
-        flake8 --exclude=migrations,ui ..;
-      fi
-
-      - echo 'travis_fold:start:grunt'
-      - pushd ui
-      - if ! -n "$DJANGO_UNIT_TESTS"; then grunt make; fi
-      - if -n "$GRUNT_TESTS"; then grunt test; fi
-      - popd
-      - echo 'travis_fold:end:grunt'
-
-      - echo 'travis_fold:start:django-unit-tests'
-      - if -n "$DJANGO_UNIT_TESTS"; then coverage run manage.py test; fi
-      - echo 'travis_fold:end:django-unit-tests'
-
-      - echo 'travis_fold:start:django-selenium-tests'
-      - if -n "$DJANGO_SELENIUM_TESTS"; then coverage run manage.py test --pattern="selenium_tests.py"; fi
-      - echo 'travis_fold:end:django-selenium-tests'
-
-      - set +e # Currently, codecov does not always exit with 0, but that should not cause travis to fail.
-services:
-  - postgresql
-sudo: required
