Re-add comments

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -40,6 +40,7 @@ install:
     if ! test -n "$GRUNT_TESTS"; then
       pip install -r requirements.txt --quiet
     fi
+  # Install geckodriver required for selenium testing
   - |
     if test -n "$DJANGO_SELENIUM_TESTS"; then
       GECKODRIVER_VERSION=v0.17.0
@@ -60,11 +61,13 @@ env:
 before_script:
   - |
     if ! test -n "$GRUNT_TESTS"; then
+      # Vagrant is not used on travis: This user is just for the database.
       createuser --createdb --no-superuser --no-createrole vagrant
       createdb -O vagrant refinery
       sudo mkdir /data
       sudo chown $USER /data
       cd refinery
+      # See http://www.stuartellis.eu/articles/erb/#running-erb-from-the-command-line
       erb config/config.json.erb > config/config.json
       python manage.py migrate --noinput
       cd ../
@@ -80,9 +83,11 @@ before_script:
     fi
 
 script:
-  - "set -e"
+  - "set -e" # Any error will cause travis to exit early and report a failure.
   - |
     if ! test -n "$GRUNT_TESTS"; then
+      # TODO: Not the same behavior as pre-commit hook.
+      # https://github.com/refinery-platform/refinery-platform/issues/1851
       flake8 --exclude=migrations,ui ..
     fi
 
